# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Ui/supplement_recommendation_app2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(946, 806)
        self.dockWidget = QtWidgets.QDockWidget(Form)
        self.dockWidget.setGeometry(QtCore.QRect(20, 10, 911, 781))
        self.dockWidget.setStyleSheet("/* QDockWidget 외곽 */\n"
"QDockWidget {\n"
"    background-color: transparent;\n"
"    border: 1px solid #616161;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* 내부 컨텐츠 배경만 (테두리 없음) */\n"
"QDockWidget QWidget {\n"
"    background-color: white;\n"
"    border: none;\n"
"    border-radius: 0px; /* 내부는 모서리 둥글지 않게 */\n"
"}\n"
"\n"
"/* 타이틀 바 */\n"
"QDockWidget::title {\n"
"    background-color: #757575;\n"
"    color: white;\n"
"    padding: 12px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    height: 30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border: 1px solid #616161;\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button {\n"
"    background: transparent;\n"
"    border: 1px solid #616161;\n"
"    icon-size: 35px;               /* 아이콘 자체 크기 */\n"
"    padding: 0px;                  /* 아이콘 여백 */\n"
"    min-width: 25px;               /* 버튼 크기 */\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"}\n"
"\n"
"\n"
"\n"
"QDockWidget::close-button {\n"
"    image: url(C:/intel_training/Ai_supplement/close_icon_off.png);\n"
"}\n"
"\n"
"QDockWidget::float-button {\n"
"    image: url(C:/intel_training/Ai_supplement/restore_icon.png);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover,\n"
"QDockWidget::float-button:hover {\n"
"    background-color: #BDBDBD;\n"
"}\n"
"\n"
"QMainWindow mainWindow;\n"
"mainWindow.setWindowIcon(QIcon(C:/intel_training/Ai_supplement/perilla_favicon.png));")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.comboBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox.setGeometry(QtCore.QRect(430, 30, 451, 31))
        self.comboBox.setStyleSheet("QComboBox\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #000000\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_url = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_url.setGeometry(QtCore.QRect(190, 560, 691, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_url.setFont(font)
        self.pushButton_url.setStyleSheet("QPushButton\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #0000ff\n"
"}")
        self.pushButton_url.setText("")
        self.pushButton_url.setObjectName("pushButton_url")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(20, 560, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(430, 70, 451, 461))
        font = QtGui.QFont()
        font.setFamily("함초롬바탕")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QTextEdit\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #000000\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(20, 30, 401, 501))
        font = QtGui.QFont()
        font.setFamily("함초롬바탕")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QTextEdit\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #000000;\n"
"}")
        self.label.setObjectName("label")
        self.dockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "추천된 제품들"))
        self.comboBox.setItemText(1, _translate("Form", "추가하기"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">제품 구매하러 가기</p></body></html>"))
        self.label_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'함초롬바탕\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'함초롬바탕\'; font-size:13pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
